In [53]:
import pandas as pad 
df=pad.read_csv('language.csv')
df.head()

,Text,language
0,klement gottwaldi surnukeha palsameeriti ning ...,Estonian
1,sebes joseph pereira thomas på eng the jesuit...,Swedish
2,ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...,Thai
3,விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...,Tamil
4,de spons behoort tot het geslacht haliclona en...,Dutch


In [54]:
df.info

<bound method DataFrame.info of                                                     Text  language
0      klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1      sebes joseph pereira thomas  på eng the jesuit...   Swedish
2      ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3      விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4      de spons behoort tot het geslacht haliclona en...     Dutch
...                                                  ...       ...
21995  hors du terrain les années  et  sont des année...    French
21996  ใน พศ  หลักจากที่เสด็จประพาสแหลมมลายู ชวา อินเ...      Thai
21997  con motivo de la celebración del septuagésimoq...   Spanish
21998  年月，當時還只有歲的她在美國出道，以mai-k名義推出首張英文《baby i like》，由...   Chinese
21999   aprilie sonda spațială messenger a nasa și-a ...  Romanian

[22000 rows x 2 columns]>

In [55]:
df.columns

Index(['Text', 'language'], dtype='object')

In [56]:
df.isnull().sum()

Text        0
language    0
dtype: int64

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
le = LabelEncoder()
y = le.fit_transform(df['language'])


In [133]:
pickle.dump(le, open("label_encoder.pkl", "wb"))

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [64]:
vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(1,3))
X = vectorizer.fit_transform(df['Text'])

In [129]:
import pickle

pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
from sklearn.naive_bayes import MultinomialNB

In [68]:
x_train,x_test ,y_train,y_test =train_test_split(X,y,test_size=.2)

In [69]:
x_train

<17600x655714 sparse matrix of type '<class 'numpy.float64'>'
	with 7814710 stored elements in Compressed Sparse Row format>

In [70]:
y_test

array([ 2,  5, 13, ..., 17, 11,  0])

In [71]:
nb=MultinomialNB()
nb.fit(x_train,y_train)

MultinomialNB()

In [72]:
nb.score(x_test,y_test)

0.9779545454545454

In [131]:
pickle.dump(nb, open("nb_model.pkl", "wb"))

In [113]:
from sklearn.svm import LinearSVC

svc = LinearSVC()
svc.fit(x_train, y_train)



LinearSVC()

In [ ]:
svc.predict(x_test)
svc.score(x_test,y_test)

In [132]:
pickle.dump(svc, open("svc_model.pkl", "wb"))

In [124]:

import numpy as np
user_input = input("Enter text: ")
text = user_input.lower()
text_vec = vectorizer.transform([text])

# SVM
pred_svc = svc.predict(text_vec)
print("SVC:", le.inverse_transform(pred_svc)[0])

# NB
pred_nb = nb.predict(text_vec)
prob_nb = np.max(nb.predict_proba(text_vec))  # confidence

print("NB :", le.inverse_transform(pred_nb)[0])
print("NB Confidence:", round(prob_nb, 3))

SVC: Chinese
NB : English
NB Confidence: 0.483


In [119]:
from sklearn.linear_model import LinearRegression

In [128]:
y_test

array([ 2,  5, 13, ..., 17, 11,  0])

In [125]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [121]:
lr.predict(x_test)

array([ 0.20846724,  1.71664952, 12.81520812, ..., 16.92674138,
       10.46545089, -1.05047502])

In [122]:
lr.score(x_test,y_test)

0.9144508548154658